[package]
name = "rust-sandbox"
version = "0.1.0"
authors = ["Tatsuya Takamura <takamura@tonchidot.com>"]

[dependencies]
rand="0.3.0"

[[bin]]
name = "hello_rust"
path = "src/hello_rust/main.rs"

[[bin]]
name = "guess"
path = "src/guess/main.rs"
